#!/bin/sh

# Export
export Changelog=$OUT/changelog.txt

if [ -f $Changelog ];
then
	rm -f $Changelog
fi

touch $Changelog

# Print something to build output
echo "Generating changelog..."

for i in $(seq 7);
do
export After_Date=`date --date="$i days ago" +%m-%d-%Y`
k=$(expr $i - 1)
	export Until_Date=`date --date="$k days ago" +%m-%d-%Y`

	# Line with after --- until was too long for a small ListView
	echo '--  ' $Until_Date  >> $Changelog
	echo >> $Changelog;

	# Cycle through every repo to find commits between 2 dates
	repo --color=never forall -pc 'git log --format="| Commit: %h | Title: %s | By: %an " --reverse --after=$After_Date --until=$Until_Date' >> $Changelog
	echo >> $Changelog;
done

# Copy changelog to system/addon.d/
cp $Changelog $OUT/system/addon.d/
