#!/bin/sh

if [ "$TO_CHANGELOG" = false ]
then
  # Do not add changelog
  echo -e "No changelog..."
  echo -e
else
  # Add changelog
  echo -e "Creating changelog..."
  echo -e
  . $ANDROID_BUILD_TOP/vendor/to/tools/changelog
fi
