#!/bin/sh

# Determine what to name the new signed package
MODVERSION=`sed -n -e'/ro\.to\.version/s/^.*=//p' $OUT/system/build.prop`

# Exports
export Changelog=$OUT/system/addon.d/changelog.txt
export Changelog2=$MODVERSION-changelog.log

if [ -f $Changelog ];
then
	cp $Changelog $OUT/$Changelog2
fi

